#include "JSONDescription.h"
#include "FormatOutputJSON.h"

const char TemplateJSON[] = "[{\n"
"	'param' : 'Ud',\n"
"	'type' : 'set',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '1',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '600',\n"
"			'max': '1000'\n"
"		}],\n"
"},\n"
"{\n"
"	'param' : 'It',\n"
"	'type' : 'set',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '2',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '125',\n"
"			'max': '2500'\n"
"		},\n"
"		{\n"
"			'rangeId' : '3',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '125',\n"
"			'max': '2500'\n"
"		},\n"
"		{\n"
"			'rangeId' : '4',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '125',\n"
"			'max': '2500'\n"
"		},\n"
"}]";

